[package]
name = "investec-transaction-buckets"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
serde = "1.0.219"
serde_json = "1.0.143"
thiserror = "2.0.12"
tokio = "1.47.1"
tokio-cron-scheduler = "0.14.0"
url = "2.5.7"
