services:
  ollama:
    image: ollama/ollama:latest
    container_name: investec-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 30
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: investec-app
    depends_on:
      ollama:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - OLLAMA_HOST=http://ollama
      - OLLAMA_PORT=11434
      - DATABASE_URL=sqlite:///app/data/transactions.db
    volumes:
      - app-data:/app/data
    restart: unless-stopped

volumes:
  ollama:
  app-data:
