services:
  postgres:
    image: postgres:18-alpine
    container_name: investec-postgres
    environment:
      POSTGRES_DB: investec_transactions
      POSTGRES_USER: investec
      POSTGRES_PASSWORD: investec_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U investec -d investec_transactions"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: investec-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 30
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: investec-app
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - OLLAMA_HOST=http://ollama
      - OLLAMA_PORT=11434
      - DATABASE_URL=postgresql://investec:investec_password@postgres:5432/investec_transactions
    restart: unless-stopped

volumes:
  postgres-data:
  ollama:
